name: typed-file-system-path

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: typed-file-system-path-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pr:
    name: Node ${{ matrix.node }} in ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['18']
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: latest
      - name: Set Node.js
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm build
      - name: Lint
        run: pnpm lint
